# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imagepack.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='imagepack.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fimagepack.proto\"n\n\timagepack\x12\x1c\n\x04imgs\x18\x01 \x03(\x0b\x32\x0e.imagepack.Mat\x12\t\n\x01x\x18\x02 \x03(\r\x1a\x38\n\x03Mat\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\x62\x06proto3')
)




_IMAGEPACK_MAT = _descriptor.Descriptor(
  name='Mat',
  full_name='imagepack.Mat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='imagepack.Mat.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='imagepack.Mat.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_data', full_name='imagepack.Mat.image_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=129,
)

_IMAGEPACK = _descriptor.Descriptor(
  name='imagepack',
  full_name='imagepack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imgs', full_name='imagepack.imgs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='imagepack.x', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_IMAGEPACK_MAT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=129,
)

_IMAGEPACK_MAT.containing_type = _IMAGEPACK
_IMAGEPACK.fields_by_name['imgs'].message_type = _IMAGEPACK_MAT
DESCRIPTOR.message_types_by_name['imagepack'] = _IMAGEPACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

imagepack = _reflection.GeneratedProtocolMessageType('imagepack', (_message.Message,), dict(

  Mat = _reflection.GeneratedProtocolMessageType('Mat', (_message.Message,), dict(
    DESCRIPTOR = _IMAGEPACK_MAT,
    __module__ = 'imagepack_pb2'
    # @@protoc_insertion_point(class_scope:imagepack.Mat)
    ))
  ,
  DESCRIPTOR = _IMAGEPACK,
  __module__ = 'imagepack_pb2'
  # @@protoc_insertion_point(class_scope:imagepack)
  ))
_sym_db.RegisterMessage(imagepack)
_sym_db.RegisterMessage(imagepack.Mat)


# @@protoc_insertion_point(module_scope)
